apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openlane-dns-com
  namespace: gateway-system
spec:
  # The secret name where cert-manager should store the signed certificate
  secretName: openlane-dns-com-tls
  dnsNames:
    - openlane-dns.com
    - "*.openlane-dns.com"
  # Duration of the certificate
  duration: 168h
  # Renew a day before the certificate expiration
  renewBefore: 24h
  # Reference the Origin CA Issuer you created above, which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: cloudflare-openlane-dns-com-api-token
