---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-openlane-dns-com-api-token
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-openlane-dns-com-api-token
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: CLOUDFLARE_OPENLANE_DNS_COM_API_TOKEN
