apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustcenter-fe
  namespace: gateway-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trustcenter-fe
  template:
    metadata:
      labels:
        app: trustcenter-fe
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
        kubernetes.io/arch: arm64
      containers:
        - name: trustcenter-fe
          image: ghcr.io/theopenlane/trust-center-fe:v0.1.11-ac-1
          ports:
            - containerPort: 3001
          env:
            - name: NEXT_PUBLIC_API_URL
              value: https://api.theopenlane.io
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: trustcenter-fe
  namespace: gateway-system
spec:
  selector:
    app: trustcenter-fe
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
