apiVersion: v2
name: openlane-gcp-bigquery
description: A Helm chart that Creates BigQuery resources through Config Connector
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
- email: support@theopenlane.io
  name: Openlane
  url: https://wwww.theopenlane.io
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/core
  - https://github.com/theopenlane/openlane-infra
home: https://www.theopenlane.io
