global:
  # -- Allows to deploy in another namespace than the release one
  # @default -- `nil`
  cnrmNamespace: ""
  # -- Google Project ID
  gcpProjectId: "myprojectid"
  # -- Keep the VPC even after the kcc resource deletion.
  deletion_policy: abandon

bigqueryDataset:
  delete_contents_on_destroy: "false"
  # -- name of the Dataset
  name: openlane-bigQueryDataset
  namespace: cnrm-gcp-dev
  access:
  - dataset: {}
    domain: ""
    groupByEmail: ""
  # -- roles list for roles writer/reader/admin
    role: ""
    routine: {}
      # datasetId: ""
      # projectId: ""
      # routineId: ""
    specialGroup: ""
  # -- email id for the gke serviceaccount
    userByEmail: ""
    view: {}
      # datasetId: ""
      # projectId: ""
      # tableId: ""
  defaultCollation: ""
  defaultEncryptionConfiguration: {}
    # kmsKeyRef:
    #   external: ""
    #   name: ""
    #   namespace: ""
  defaultPartitionExpirationMs: ""
  defaultTableExpirationMs: ""
  # -- user defines defination
  description: ""
  # -- friendly defination
  friendlyName: ""
  isCaseInsensitive: ""
  # -- location of the dataset
  location: ""
  maxTimeTravelHours: ""
  projectRef: {}
    # external: ""
    # name: ""
    # namespace: ""
  resourceID: ""
  storageBillingModel: ""
