apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisCluster
metadata:
  labels:
    label-one: "value-one"
  name: rediscluster-sample
spec:
  shardCount: 6
  pscConfigs:
  - networkRef:
      name: rediscluster-dep
  location: us-central1
  projectRef:
    external: ${PROJECT_ID?}
  replicaCount: 2
  nodeType: REDIS_STANDARD_SMALL
  transitEncryptionMode: TRANSIT_ENCRYPTION_MODE_SERVER_AUTHENTICATION
  authorizationMode: AUTH_MODE_IAM_AUTH
  redisConfigs:
    maxmemory-policy: volatile-ttl
  zoneDistributionConfig:
    mode: SINGLE_ZONE
    zone: us-central1-b
  persistenceConfig:
    mode: AOF
    aofConfig:
      appendFsync: EVERYSEC
  deletionProtectionEnabled: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: rediscluster-dep
spec:
  description: Test network for the project
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: rediscluster-dep
spec:
  ipCidrRange: 10.128.0.0/20
  region: us-central1
  networkRef:
    name: rediscluster-dep
---
apiVersion: networkconnectivity.cnrm.cloud.google.com/v1alpha1
kind: NetworkConnectivityServiceConnectionPolicy
metadata:
  name: rediscluster-dep
  labels:
    label-one: "value-one"
spec:
  projectRef:
    external: ${PROJECT_ID?}
  location: us-central1
  serviceClass: "gcp-memorystore-redis"
  description: "Service Connection Policy for redis"
  networkRef:
    name: rediscluster-dep
  pscConfig:
    subnetworkRefs:
    - name: rediscluster-dep
