{{- if .Values.enabled }}
apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  name: {{ .Values.redisInstance.name | quote }}
  namespace: {{ include "openlane-gcp-memorystore.namespace" . }}
  annotations:
{{- if .Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
{{- end }}
{{- if .Values.global.forceDestroy }}
    cnrm.cloud.google.com/force-destroy: "true"
{{- end }}
{{- if .Values.global.skipUnspecifiedFields }}
    cnrm.cloud.google.com/state-into-spec: absent
{{- end }}
    cnrm.cloud.google.com/project-id: {{ .Values.global.gcpProjectId | quote }}
  labels:
    {{- include "openlane-gcp-memorystorelabels" . | nindent 4 }}
spec:
  region: {{ .Values.redisInstance.region | quote }}
  tier: {{ .Values.redisInstance.tier | quote }}
  memorySizeGb: {{ .Values.redisInstance.memorySizeGb }}
  {{- if .Values.redisInstance.displayName }}
  displayName: {{ .Values.redisInstance.displayName | quote }}
  {{- end }}
  {{- if .Values.redisInstance.authNetworkRef.external }}
  authorizedNetworkRef:
    external: {{ .Values.redisInstance.authNetworkRef.external | quote }}
  {{- end }}
  redisVersion: {{ .Values.redisInstance.redisVersion | quote }}
  {{- if .Values.redisInstance.redisConfigs }}
  redisConfigs:
{{ toYaml .Values.redisInstance.redisConfigs | indent 4 }}
  {{- end }}
{{- end }}
