# Default values for the Config Controller chart
# Enable or disable the entire chart (boolean)
enabled: true

# Configuration for ConfigControllerInstance resource
configController:
  # Resource name (string)
  name: "openlane-config-controller"
  # GCP project reference
  projectRef:
    # Project resource path, e.g., projects/{projectId} (string)
    external: ""
    # Optional ref name (string)
    name: ""
    # Optional ref namespace (string)
    namespace: ""
  # Location for Config Controller (string)
  location: "us-central1"
  # Optional resourceID override (string)
  resourceID: ""
  # Enable private endpoint (boolean)
  usePrivateEndpoint: false

  # Management configuration
  managementConfig:
    # Full management configuration settings (map)
    fullManagementConfig:
      # CIDR block for cluster (string)
      clusterCidrBlock: ""
      # Named range for cluster (string)
      clusterNamedRange: ""
      # Master IPv4 CIDR block (string)
      masterIPv4CidrBlock: ""
      # VPC network reference (string)
      networkRef:
        external: ""
      # Services CIDR block (string)
      servicesCidrBlock: ""
      # Named range for services (string)
      servicesNamedRange: ""
    # Standard management config settings (map)
    standardManagementConfig:
      # CIDR block for cluster (string)
      clusterCidrBlock: ""
      # Named range for cluster (string)
      clusterNamedRange: ""
      # Master IPv4 CIDR block (string)
      masterIPv4CidrBlock: ""
      # VPC network reference (string)
      networkRef:
        external: ""
      # Services CIDR block (string)
      servicesCidrBlock: ""
      # Named range for services (string)
      servicesNamedRange: ""
