default_stages: [pre-commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.37.0
    hooks:
      - id: typos
  - repo: https://github.com/norwoodj/helm-docs
    rev:  v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
          - --output-file=HELM.md
          - --template-files=HELM.md.gotmpl
          - --skip-version-footer
          - --sort-values-order=file
