title: Openlane helm charts
description: Central repository hosting helm charts for Openlane infrastructure and application deployment
theme: minima
url: "https://charts.theopenlane.io/"
repo_name: openlane-infra

exclude:
  - .gitignore
