---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  labels:
    gateway: prod-global-gateway
  namespace: argocd
spec:
  parentRefs:
  - name: prod-global-gateway
    namespace: argocd
    sectionName: https
  hostnames:
  - "argocd.prod.theopenlane.io"
  - "argo.theopenlane.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: prod-argocd-server
      port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: http-redirect
spec:
  parentRefs:
    - namespace: argocd
      name: prod-global-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
