apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-trustcenter
  namespace: openlane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trustcenter
  namespace: openlane
  labels:
    {{- include "trustcenter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trustcenter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trustcenter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-trustcenter
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
        kubernetes.io/arch: arm64
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - trustcenter
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "trustcenter.selectorLabels" . | nindent 12 }}
      containers:
        - name: trustcenter
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3001
              protocol: TCP
              name: http
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health-check
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-trustcenter
  namespace: openlane
  labels:
    {{- include "trustcenter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "trustcenter.selectorLabels" . | nindent 4 }}
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-trustcenter-https-route
  namespace: openlane
  labels:
    {{- include "trustcenter.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: trustcenter-gateway
      sectionName: https
      namespace: gateway-system
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-trustcenter
          port: 3001
          namespace: openlane
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Release.Name }}-trustcenter
  namespace: openlane
  labels:
    {{- include "trustcenter.labels" . | nindent 4 }}

spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 3001
        requestPath: /health-check
  targetRef:
    group: ""
    kind: Service
    name: {{ .Release.Name }}-trustcenter
