apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: oauth2-healthcheck
  namespace: grafana
spec:
  default:
    unhealthyThreshold: 10
    healthyThreshold: 1
    timeoutSec: 5
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /ready
        portName: http
  targetRef:
    group: ""
    kind: Service
    name: grafana-oauth2
