apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http-route
  namespace: grafana
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.theopenlane.org
spec:
  parentRefs:
  - name: openlane-org-gateway
    namespace: gateway-system
    sectionName: https
  hostnames:
    - grafana.theopenlane.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
            - name: X-Auth-Request-Redirect
              value: "https://grafana.theopenlane.org/oauth2/start?rd=https://grafana.theopenlane.org/"
      backendRefs:
        - name: grafana-oauth2
          port: 80
  - matches:
      - path:
          type: PathPrefix
          value: /oauth2/
    backendRefs:
      - name: grafana-oauth2
        port: 80
