apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http-route
  namespace: grafana
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.theopenlane.org
spec:
  parentRefs:
  - name: openlane-org-gateway
    namespace: gateway-system
    sectionName: https
  hostnames:
    - grafana.theopenlane.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      - name: grafana-oauth2
        port: 4180
  - matches:
    - path:
        type: PathPrefix
        value: /oauth2/
    backendRefs:
      - name: grafana-oauth2
        port: 4180
