apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill-cloudsql
  namespace: windmill
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: windmill-cloudsql
    creationPolicy: Owner
  data:
    - secretKey: dburi
      remoteRef:
        key: WINDMILL_DATASTORE_URI
    - secretKey: licenseKey
      remoteRef:
        key: WINDMILL_ENTERPRISE_LICENSE
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill-enterprise-license
  namespace: windmill
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: windmill-enterprise-license
    creationPolicy: Owner
  data:
    - secretKey: licenseKey
      remoteRef:
        key: WINDMILL_ENTERPRISE_LICENSE
