apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: windmill-http-route
  namespace: windmill
  annotations:
    external-dns.alpha.kubernetes.io/hostname: windmill.theopenlane.org
spec:
  parentRefs:
  - name: openlane-org-gateway
    namespace: gateway-system
    sectionName: https
  hostnames:
    - windmill.theopenlane.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /ws/
    backendRefs:
    - name: windmill-lsp
      port: 3001
  - matches:
    - path:
        type: PathPrefix
        value: /ws_mp/
    backendRefs:
    - name: windmill-multiplayer
      port: 3002
  - matches:
    - path:
        type: PathPrefix
        value: /api/srch/
    backendRefs:
    - name: windmill-indexer
      port: 8000
  - matches:
    - path:
        type: PathPrefix
        value: /api/mcp/
    backendRefs:
    - name: windmill-mcp
      port: 8000
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: windmill-app
      port: 8000
