apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  labels:
{{- include "service-account.labels" . | nindent 4 }}
  name: {{ .Values.name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.global.gcpProjectId }}
    {{- if .Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
    {{- with .Values.annotations }}
{{- . | toYaml | nindent 4 }}
    {{- end }}
  namespace: {{ include "service-account.namespace" . }}
spec:
  displayName: {{ .Values.displayName | quote }}
  description: {{ .Values.description | quote }}
