{{- if .Values.key.create }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  labels:
{{- include "service-account.labels" . | nindent 4 }}
  name: {{ .Values.name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.global.gcpProjectId }}
    {{- if .Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
    cnrm.cloud.google.com/create-gsa-key-secret: {{ .Values.key.importAsSecret }}
    {{- with .Values.annotations }}
{{- . | toYaml | nindent 4 }}
    {{- end }}
  namespace: {{ include "service-account.namespace" . }}
spec:
  publicKeyType: TYPE_X509_PEM_FILE
  keyAlgorithm: KEY_ALG_RSA_2048
  privateKeyType: TYPE_GOOGLE_CREDENTIALS_FILE
  serviceAccountRef:
    name: {{ .Values.name }}
{{- end }}
