version: 0.1.0
apiVersion: v2
appVersion: 1.0.0
description: Install only the Prometheus Operator CRDs on GKE clusters for Openlane
name: openlane-prometheus-crds
type: application
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/openlane-infra
home: https://docs.theopenlane.io
dependencies:
  - name: prometheus-operator-crds
    version: 22.0.2
    repository: https://prometheus-community.github.io/helm-charts
