steps:
  - label: ":helm: Lint Chart"
    plugins:
      - docker#v3.14.0:
          image: alpine/helm:3.11.1
    commands:
      - helm lint .

  - label: ":helm: Lint Charts"
    plugins:
      - docker#v3.14.0:
          image: alpine/helm:3.11.2
          command: helm lint charts/*

  - label: ":hammer: Render Dev"
    plugins:
      - docker#v3.14.0:
          image: alpine/helm:3.11.1
    commands:
      - mkdir -p rendered/dev
      - helm template openlane-infra -f values-dev.yaml > rendered/dev/all.yaml

  - label: ":hammer: Render Prod"
    plugins:
      - docker#v3.14.0:
          image: alpine/helm:3.11.1
    commands:
      - mkdir -p rendered/prod
      - helm template openlane-infra -f values-prod.yaml > rendered/prod/all.yaml

  - label: ":mag: Validate YAML"
    plugins:
      - docker#v3.14.0:
          image: cytopia/yamllint
    commands:
      - yamllint rendered/

  - label: ":bash: Test Packaging"
    command: |
      for chart in charts/*; do
        helm dependency update "$chart"
        helm package "$chart"
      done

  - label: ":git: Commit and Push Changes"
    commands:
      - |
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git config user.name "buildkite-bot"
          git config user.email "ci@openlane.io"
          git add rendered/
          git commit -m "Update rendered manifests [skip ci]"
          git push
        fi