{{- $globalValues := default dict .Values.global -}}
{{- $gcpProjectId := default .Values.gcpProjectId $globalValues.gcpProjectId -}}
{{- $abandon := default .Values.abandon $globalValues.abandon -}}

{{- range .Values.members }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    {{- if $abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
    cnrm.cloud.google.com/project-id: {{ $gcpProjectId | quote }}
  labels:
    {{- include "gcp-iam-policy-members.labels" $ | nindent 4 }}
  name: {{ .name | default (include "gcp-iam-policy-members.fullname" $) }}
  namespace: {{ include "gcp-iam-policy-members.namespace" $ }}
spec:
  {{- if .condition }}
  {{- if and .condition.title .condition.expression }}
  condition:
    title: {{ .condition.title }}
    expression: {{ .condition.expression }}
    description: {{ .condition.description }}
  {{- end }}
  {{- end }}

  member: {{ .member | quote }}

  {{- if .role }}
  role: {{ .role }}
  {{- else }}
  {{- fail "Error: role is required" }}
  {{- end }}

{{- if .memberFrom }}
  memberFrom:
  {{- if .memberFrom.bigQueryConnectionConnectionRef }}
    {{- if and .memberFrom.bigQueryConnectionConnectionRef.name .memberFrom.bigQueryConnectionConnectionRef.type }}
      bigQueryConnectionConnectionRef:
        name: {{ .memberFrom.bigQueryConnectionConnectionRef.name }}
        type: {{ .memberFrom.bigQueryConnectionConnectionRef.type }}
        namespace: {{ .memberFrom.bigQueryConnectionConnectionRef.namespace }}
    {{- end }}
  {{- end }}

  {{- if .memberFrom.logSinkRef }}
  {{- if .memberFrom.logSinkRef.name }}
    logSinkRef:
      name: {{ .memberFrom.logSinkRef.name }}
      namespace: {{ .memberFrom.logSinkRef.namespace }}
  {{- end }}
  {{- end }}

  {{- if .memberFrom.serviceAccountRef }}
  {{- if .memberFrom.serviceAccountRef.name }}
    serviceAccountRef:
      name: {{ .memberFrom.serviceAccountRef.name }}
      namespace: {{ .memberFrom.serviceAccountRef.namespace }}
  {{- end }}
  {{- end }}

  {{- if .memberFrom.serviceIdentityRef }}
  {{- if .memberFrom.serviceIdentityRef.name }}
    serviceIdentityRef:
      name: {{ .memberFrom.serviceIdentityRef.name }}
      namespace: {{ .memberFrom.serviceIdentityRef.namespace }}
  {{- end }}
  {{- end }}

  {{- if .memberFrom.sqlInstanceRef }}
  {{- if .memberFrom.sqlInstanceRef.name }}
    sqlInstanceRef:
      name: {{ .memberFrom.sqlInstanceRef.name }}
      namespace: {{ .memberFrom.sqlInstanceRef.namespace }}
  {{- end }}
  {{- end }}
{{- end }}
  {{- if .resourceRef }}
  {{- if and .resourceRef.kind }}
  resourceRef:
    kind: {{ .resourceRef.kind }}
    {{- if .resourceRef.external }}
    external: {{ .resourceRef.external }}
    {{- else if .resourceRef.name }}
    name: {{ .resourceRef.name }}
    {{- end }}
    {{- if .resourceRef.apiVersion }}
    apiVersion: {{ .resourceRef.apiVersion }}
    {{- end }}
    {{- if .resourceRef.namespace }}
    namespace: {{ .resourceRef.namespace }}
    {{- end }}
  {{- else }}
  {{- fail "resourceRef.kind is required" }}
  {{- end }}
  {{- else }}
  {{- fail "Error: resourceRef is required" }}
  {{- end }}
{{- end }}
