# See https://github.com/helm/chart-testing#configuration
remote: origin
chart-dirs:
  - charts
helm-extra-args: --timeout=500
chart-repos:
  - oauth2-proxy=https://oauth2-proxy.github.io/manifests
check-version-increment: true