{{- if .Values.enabled }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeGlobalAddress
metadata:
  name: {{ .Values.globalAddress.name | quote }}
  namespace: {{ include "gcp-lb.namespace" . }}
  annotations:
{{- if .Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
{{- end }}
{{- if .Values.global.forceDestroy }}
    cnrm.cloud.google.com/force-destroy: "true"
{{- end }}
{{- if .Values.global.skipUnspecifiedFields }}
    cnrm.cloud.google.com/state-into-spec: absent
{{- end }}
    cnrm.cloud.google.com/project-id: {{ .Values.global.gcpProjectId | quote }}
  labels:
    {{- include "gcp-lb.labels" . | nindent 4 }}
spec:
  addressType: {{ .Values.globalAddress.addressType | quote }}
  ipVersion: {{ .Values.globalAddress.ipVersion | quote }}
{{- end }}
