{{- if .Values.globalAddress.enabled }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: {{ .Values.globalAddress.name | quote }}
  namespace: {{ include "gcp-lb.namespace" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId | quote }}
spec:
  addressType: {{ .Values.globalAddress.addressType | quote }}
  ipVersion: {{ .Values.globalAddress.ipVersion | quote }}
  description: {{ .Values.globalAddress.description | quote }}
  networkTier: {{ .Values.globalAddress.networkTier | quote }}
  prefixLength: {{ .Values.globalAddress.prefixLength }}
  purpose: {{ .Values.globalAddress.purpose | quote }}
  {{- if .Values.globalAddress.networkRef.external }}
  networkRef:
    external: {{ .Values.globalAddress.networkRef.external | quote }}
  {{- end }}
  {{- if .Values.globalAddress.subnetworkRef.external }}
  subnetworkRef:
    external: {{ .Values.globalAddress.subnetworkRef.external | quote }}
  {{- end }}
{{- end }}
