{{- if .Values.sslPolicy.enabled }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSslPolicy
metadata:
  name: {{ .Values.sslPolicy.name | quote }}
  namespace: {{ include "gcp-lb.namespace" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId | quote }}
spec:
  profile: {{ .Values.sslPolicy.profile | quote }}
  minTlsVersion: {{ .Values.sslPolicy.minTlsVersion | quote }}
  {{- if .Values.sslPolicy.customFeatures }}
  customFeatures:
{{ toYaml .Values.sslPolicy.customFeatures | indent 4 }}
  {{- end }}
{{- end }}
