{{- if .Values.backendService.enabled }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: {{ .Values.backendService.name | quote }}
  namespace: {{ include "gcp-lb.namespace" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId | quote }}
spec:
  protocol: {{ .Values.backendService.protocol | quote }}
  portName: {{ .Values.backendService.portName | quote }}
  loadBalancingScheme: {{ .Values.backendService.loadBalancingScheme | quote }}
  timeoutSec: {{ .Values.backendService.timeoutSec }}
  connectionDraining:
    drainingTimeoutSec: {{ .Values.backendService.connectionDraining.drainingTimeoutSec }}
  enableCdn: {{ .Values.backendService.enableCdn }}
  affinityCookieTtlSec: {{ .Values.backendService.affinityCookieTtlSec }}
  healthChecks:
{{ toYaml .Values.backendService.healthChecks | indent 4 }}
  backends:
{{ toYaml .Values.backendService.backends | indent 4 }}
{{- end }}
