{{- if .Values.httpsProxy.enabled }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHttpsProxy
metadata:
  name: {{ .Values.httpsProxy.name | quote }}
  namespace: {{ include "gcp-lb.namespace" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId | quote }}
spec:
  urlMapRef:
    external: {{ .Values.httpsProxy.urlMapRef | quote }}
  sslCertificates:
{{ toYaml .Values.httpsProxy.sslCertificates | indent 4 }}
  {{- if .Values.httpsProxy.sslPolicyRef }}
  sslPolicyRef:
    external: {{ .Values.httpsProxy.sslPolicyRef | quote }}
  {{- end }}
{{- end }}
