{{- if .Values.httpProxy.enabled }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHttpProxy
metadata:
  name: {{ .Values.httpProxy.name | quote }}
  namespace: {{ include "gcp-lb.namespace" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId | quote }}
spec:
  urlMapRef:
    external: {{ .Values.httpProxy.urlMapRef | quote }}
{{- end }}
