{{- if .Values.enabled }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  name: {{ .Values.healthCheck.name | quote }}
  namespace: {{ include "gcp-lb.namespace" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectId | quote }}
spec:
  checkIntervalSec: {{ .Values.healthCheck.checkIntervalSec }}
  timeoutSec: {{ .Values.healthCheck.timeoutSec }}
  healthyThreshold: {{ .Values.healthCheck.healthyThreshold }}
  unhealthyThreshold: {{ .Values.healthCheck.unhealthyThreshold }}
  {{- if .Values.healthCheck.tcpHealthCheck }}
  tcpHealthCheck:
{{ toYaml .Values.healthCheck.tcpHealthCheck | indent 4 }}
  {{- end }}
  {{- if .Values.healthCheck.httpHealthCheck }}
  httpHealthCheck:
    port: {{ .Values.healthCheck.httpHealthCheck.port }}
    requestPath: {{ .Values.healthCheck.httpHealthCheck.requestPath | quote }}
  {{- end }}
{{- end }}
