{{- if .Values.databases.enabled }}
{{- range .Values.databases.items }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ .name | quote }}
  namespace: {{ include "gcp-cloudsql-postgresql.namespace" $ }}
spec:
  instanceRef:
    name: {{ .Values.sqlInstance.name | quote }}
  charset: {{ .charset | quote }}
  collation: {{ .collation | quote }}
{{- end }}
{{- end }}
