{{- if .Values.databases.enabled }}
{{- range .Values.databases.items }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ .name | quote }}
  namespace: {{ include "openlane-gcp-cloudsql.namespace" $ }}
  annotations:
{{- if $.Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
{{- end }}
{{- if $.Values.global.forceDestroy }}
    cnrm.cloud.google.com/force-destroy: "true"
{{- end }}
{{- if $.Values.global.skipUnspecifiedFields }}
    cnrm.cloud.google.com/state-into-spec: absent
{{- end }}
    cnrm.cloud.google.com/project-id: {{ $.Values.global.gcpProjectId | quote }}
spec:
  instanceRef:
    name: {{ $.Values.name | quote }}
  charset: {{ .charset | quote }}
  collation: {{ .collation | quote }}
{{- end }}
{{- end }}
