{{- if $.Values.users.enabled }}
{{- range $.Values.users.items }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ .name | quote }}
  namespace: {{ include "openlane-gcp-cloudsql.namespace" $ }}
  annotations:
{{- if $.Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
{{- end }}
{{- if $.Values.global.forceDestroy }}
    cnrm.cloud.google.com/force-destroy: "true"
{{- end }}
{{- if $.Values.global.skipUnspecifiedFields }}
    cnrm.cloud.google.com/state-into-spec: absent
{{- end }}
    cnrm.cloud.google.com/project-id: {{ $.Values.global.gcpProjectId | quote }}
spec:
  instanceRef:
    name: {{ $.Values.name | quote }}
  name: {{ .name | quote }}
  host: {{ .host | quote }}
  type: {{ .type | quote }}
  passwordSecretRef:
    secretRef:
      name: {{ .passwordSecretRef.secretRef.name | quote }}
      key: {{ .passwordSecretRef.secretRef.key | quote }}
{{- end }}
{{- end }}
