apiVersion: v2
appVersion: 0.1.0
description: Deploys external-dns and its monitoring
maintainers:
- email: support@theopenlane.io
  name: Openlane
name: openlane-external-dns
version: 0.1.1
dependencies:
  - name: external-dns
    version: 1.16.1
    repository: "https://kubernetes-sigs.github.io/external-dns/"
    alias: externaldns
  - name: openlane-gcp-workload-identity
    version: 0.1.0
    repository: "https://theopenlane.github.io/openlane-infra"
    alias: workloadIdentity
    tags:
      - configConnector
  - name: openlane-gcp-iam-policy-members
    version: 0.1.0
    repository: "https://theopenlane.github.io/openlane-infra"
    alias: iamPolicyMembers
    tags:
      - configConnector