---
# Source: openlane-external-dns/charts/externaldns/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-externaldns
  namespace: argocd
  labels:
    helm.sh/chart: externaldns-1.16.1
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: openlane-external-dns/charts/externaldns/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prod-externaldns
  labels:
    helm.sh/chart: externaldns-1.16.1
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["services","endpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
---
# Source: openlane-external-dns/charts/externaldns/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prod-externaldns-viewer
  labels:
    helm.sh/chart: externaldns-1.16.1
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prod-externaldns
subjects:
  - kind: ServiceAccount
    name: prod-externaldns
    namespace: argocd
---
# Source: openlane-external-dns/charts/externaldns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prod-externaldns
  namespace: argocd
  labels:
    helm.sh/chart: externaldns-1.16.1
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: prod
  ports:
    - name: http
      port: 7979
      targetPort: http
      protocol: TCP
---
# Source: openlane-external-dns/charts/externaldns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-externaldns
  namespace: argocd
  labels:
    helm.sh/chart: externaldns-1.16.1
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: externaldns
      app.kubernetes.io/instance: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: externaldns
        app.kubernetes.io/instance: prod
    spec:
      automountServiceAccountToken: true
      serviceAccountName: prod-externaldns
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: external-dns
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          image: registry.k8s.io/external-dns/external-dns:v0.16.1
          imagePullPolicy: IfNotPresent
          args:
            - --log-level=info
            - --log-format=json
            - --interval=1m
            - --source=service
            - --source=ingress
            - --source=gateway
            - --source=httproute
            - --policy=upsert-only
            - --registry=txt
            - --txt-owner-id=external-dns
            - --domain-filter=theopenlane.org
            - --provider=google
          ports:
            - name: http
              protocol: TCP
              containerPort: 7979
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
---
# Source: openlane-external-dns/charts/iamPolicyMembers/templates/iam-policy-members.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/project-id: "prod-apps-project"
  labels:
    helm.sh/chart: iamPolicyMembers-0.1.0
    app.kubernetes.io/name: iamPolicyMembers
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
  name: external-dns-gsa
  namespace: config-control
spec:

  member: "serviceAccount:prod-external-dns@prod-apps-project.iam.gserviceaccount.co"
  role: roles/dns.admin
  resourceRef:
    kind: Project
    external: prod-apps-project
---
# Source: openlane-external-dns/charts/workloadIdentity/templates/iampolicy.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: prod-external-dns-workload-identity
  namespace: config-control
  labels:
    helm.sh/chart: workloadIdentity-0.1.0
    app.kubernetes.io/name: workloadIdentity
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cnrm.cloud.google.com/project-id: prod-apps-project
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  resourceRef:
    kind: IAMServiceAccount
    name: "prod-external-dns"
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:prod-apps-project.svc.id.goog[external-dns/external-dns]
---
# Source: openlane-external-dns/charts/workloadIdentity/templates/serviceaccount.yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: prod-apps-project
    cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    helm.sh/chart: workloadIdentity-0.1.0
    app.kubernetes.io/name: workloadIdentity
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
  name: prod-external-dns
  namespace: config-control
spec:
  displayName:  prod-external-dns
