version: 0.1.1
apiVersion: v2
appVersion: 1.0.0
description: A Helm chart to deploy OpenFGA Server for Openlane
name: openlane-eso
type: application
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/openlane-infra
home: https://docs.theopenlane.io
dependencies:
  - name: openfga
    repository: https://openfga.github.io/helm-charts
    alias: openfga
    version: 0.2.44
