---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudsql-credentials-ext
  namespace: openfga
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudsql-credentials
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: OPENFGA_DATASTORE_URI
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: preshared-keys-ext
  namespace: openfga
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: preshared-keys
    creationPolicy: Owner
  data:
    - secretKey: keys
      remoteRef:
        key: OPENFGA_AUTHN_PRESHARED_KEYS
