---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudsql-credentials
  namespace: openfga
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudsql-credentials
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: OPENFGA_DATASTORE_URI
