apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: openfga-metrics
  namespace: openfga
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openfga
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s