apiVersion: v2
name: openlane-gcp-bucket
version: 0.1.0
appVersion: 0.1.0
description: A Helm chart for creating a GCP Bucket via Config Connector
maintainers:
- email: support@theopenlane.io
  name: Openlane
type: application