# Default values for the Project chart
# Enable or disable the entire chart (boolean)
enabled: true

# Annotations for project resource
annotations:
  # Auto-create default network (boolean)
  autoCreateNetwork: false

# Project specification
project:
  # Display name of the project (string, required)
  name: ""
  # Optional resourceID override (string)
  resourceID: ""
  # Billing account reference (string, required)
  billingAccountRef:
    external: ""
  # Folder reference (string, optional)
  folderRef:
    external: ""
  # Organization reference (string, optional)
  organizationRef:
    external: ""

# List of APIs to enable on the project
enableAPIs:
  - service: ""  # e.g., compute.googleapis.com

# IAM bindings to apply to the project
iamBindings:
  - role: ""     # e.g., roles/viewer
    members:    # array of member strings
      - ""
