version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task --list

  lint:
    desc: Lint chart
    cmds:
      - helm lint

  template:
    desc: Render chart templates
    cmds:
      - helm dependency build
      - helm template . --include-crds --skip-tests --output-dir rendered

  test:
    desc: Run tests
    cmds:
      - helm test --cleanup

  chart:test:
    desc: Run ct tests
    cmds:
      - ct lint --all --chart-dirs . --validate-maintainers=false
