global:
  # -- Allows to deploy in another namespace than the release one
  # @default -- `nil`
  cnrmNamespace: ""
  # -- Google Project ID
  gcpProjectId: myprojectid
  # -- If true, Keep the Compute Router even after the kcc resource deletion.
  abandon: true

# -- Add annotations to the Compute Router.
annotations: {}

# -- Name of the Compute Router.
name: "openlane-router"
# -- A text description of the Compute Router. Must be less than or equal to 256 UTF-8 bytes.
description: "Compute Router for managing BGP routing"
# -- Immutable. Region where the router resides.
region: us-central1
# -- Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default.
resourceID:
# -- Immutable. Indicates if a router is dedicated for use with encrypted VLAN attachments (interconnectAttachments).
encryptedInterconnectRouter:

# -- A reference to the network to which this router belongs.
networkRef:
  # -- Allowed value: The `selfLink` field of a `ComputeNetwork` resource.
  external: ""
  # -- Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
  name: "openlane-vpc"
  # -- Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
  namespace: ""

# -- BGP information specific to this router.
bgp:
  # -- Local BGP Autonomous System Number (ASN). Must be an RFC6996 private ASN, either 16-bit or 32-bit. The value will be fixed for this router resource. All VPN tunnels that link to this router will have the same local ASN.
  asn:
  # -- User-specified flag to indicate which mode to use for advertisement. Default value: "DEFAULT" Possible values: ["DEFAULT", "CUSTOM"].
  advertiseMode: "DEFAULT"
  # -- User-specified list of prefix groups to advertise in custom mode. This field can only be populated if advertiseMode is CUSTOM and is advertised to all peers of the router. These groups will be advertised in addition to any specified prefixes. Leave this field blank to advertise no custom groups. This enum field has the one valid value: ALL_SUBNETS.
  advertisedGroups: []
  # -- User-specified list of individual IP ranges to advertise in custom mode. This field can only be populated if advertiseMode is CUSTOM and is advertised to all peers of the router. These IP ranges will be advertised in addition to any specified groups. Leave this field blank to advertise no custom IP ranges.
  advertisedIpRanges:
      # -- User-specified description for the IP range.
    - description:
      # -- The IP range to advertise. The value must be a CIDR-formatted string.
      range:
  # -- The interval in seconds between BGP keepalive messages that are sent to the peer. Hold time is three times the interval at which keepalive messages are sent, and the hold time is the maximum number of seconds allowed to elapse between successive keepalive messages that BGP receives from a peer. BGP will use the smaller of either the local hold time value or the peer's hold time value as the hold time for the BGP connection between the two peers. If set, this value must be between 20 and 60. The default is 20.
  keepaliveInterval: 20
