project:
  apis:
  - container.googleapis.com
  - cloudsql.googleapis.com
  - storage.googleapis.com
  - bigquery.googleapis.com
  - redis.googleapis.com
  - dns.googleapis.com
  - iam.googleapis.com
  - cloudresourcemanager.googleapis.com
  - logging.googleapis.com
  - monitoring.googleapis.com
  displayName: prod-apps-project
  folderRef: folders/prod-apps
  gcpProjectName: Openlane Application
  id: "323616316362"
  name: prod-apps-project
orgId: "319013011373"
billingAccountId: "01AC20-2CEAE3-8BB367"
primaryRegion: "us-central1"
kms:
  enabled: true
  keyName: openlane-default-key
  keyRingName: openlane-default-keyring
  location: us-central1
commonAppConfig:
  bigquery:
    cmekEnabled: true
    enabled: true
    location: us-central1
  cloudsql:
    cmekEnabled: true
    enabled: true
    instanceName: openlane-prod-sql
    tier: db-custom-2-8192
    version: POSTGRES_14
  dnsZone:
    domainName: prod.theopenlane.io
    enabled: true
    name: prod-openlane-dns-zone
gkeCluster:
  addonsConfig:
    configConnectorConfig:
      enabled: true
    dnsCacheConfig:
      enabled: true
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    gcpFilestoreCsiDriverConfig:
      enabled: true
    gcsFuseCsiDriverConfig:
      enabled: true
    gkeBackupAgentConfig:
      enabled: true
    horizontalPodAutoscaling:
      disabled: false
    httpLoadBalancing:
      disabled: false
    networkPolicyConfig:
      disabled: true
  authenticatorGroupsConfig:
    securityGroup: gke-security-groups@theopenlane.io
  datapathProvider: ADVANCED_DATAPATH
  enableAutopilot: false
#  clusterAutoscaling:
#    serviceAccountRef: {}
#    autoProvisioningDefaults:
#      management:
#        autoRepair: true
#        autoUpgrade: true
#        upgradeOptions:
#          autoUpgradeStartTime: "05:00"
  enableIntranodeVisibility: true
  enableShieldedNodes: true
  enabled: true
  identityServiceConfig:
    enabled: true
  ipAllocationPolicy:
    enabled: true
    additionalPodRangesConfig:
      podRangeNames:
      - name: gke-pods
      - name: gke-services
    useIpAliases: true
  loggingConfig:
    enableComponents:
    - SYSTEM_COMPONENTS
    - API_SERVER
    - CONTROLLER_MANAGER
    - SCHEDULER
    - WORKLOADS
    loggingService: logging.googleapis.com/kubernetes
  machineType: e2-standard-4
  masterAuthorizedNetworksConfig:
    cidrBlocks: []
    enabled: false
  monitoringConfig:
    advancedDatapathObservabilityConfig:
      enableMetrics: true
    enableComponents:
    - SYSTEM_COMPONENTS
    managedPrometheus:
      enabled: true
    monitoringService: monitoring.googleapis.com/kubernetes
  nodeCount: 3
  privateClusterConfig:
    enablePrivateNodes: true
  releaseChannel: REGULAR
  serviceExternalIpsConfig:
    enabled: true
  workloadIdentityEnabled: true
memorystore:
  enabled: true
  instanceName: openlane-prod-redis
  memorySizeGb: 5
  tier: STANDARD_HA
  primaryRegion: us-central1
storage:
  cmekEnabled: true
  enabled: true
  location: us-central1
envName: "prod"
envCapitalizedName: "Prod"
sharedVpcHostProjectId: "prod-apps-project"
isSharedVpcHost:
  true
isSignalsProject:
  true
isKmsProject:
  true
logSinks:
  orgAudit:
    enabled: true
    destinationBucketName: "openlane-central-logs-bucket"
    destinationDatasetName: "openlane_central_logs_dataset"
network:
  name: prod-shared-vpc
  subnets:
    gkePodsSecondary:
      ipCidrRange: 10.0.32.0/16
      name: gke-pods
    gkePrimary:
      ipCidrRange: 10.1.0.0/20
      name: gke-primary-prod
      privateIpGoogleAccess: true
      secondaryIpRanges:
        - ipCidrRange: 10.1.32.0/16
          rangeName: gke-pods-prod
        - ipCidrRange: 10.1.16.0/20
          rangeName: gke-services-prod
    gkeServicesSecondary:
      ipCidrRange: 10.0.16.0/20
      name: gke-services
    internalApps:
      ipCidrRange: 10.1.48.0/20
      name: prod-apps-subnet-primary
      privateIpGoogleAccess: true
bigquery:
  cmekEnabled: true
  enabled: true
  location: us-central1
cloudsql:
  cmekEnabled: true
  enabled: true
  instanceName: openlane-prod-sql
  tier: db-custom-2-8192
  version: POSTGRES_14
dnsZone:
  domainName: prod.theopenlane.io
  enabled: true
  name: prod-openlane-dns-zone
