{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager.config.secretName" . | quote }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
data:
  alertmanager.yaml: {{ include "alertmanager.config" . | b64enc }}
{{- end }}

{{- if and .Values.oidc.enabled .Values.oidc.secret.create }}
---
apiVersion: "v1"
kind: Secret
metadata:
  name: {{ include "alertmanager.oidc.secretName" . | quote }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
  {{- if .Values.oidc.secret.annotations }}
  annotations:
  {{- toYaml .Values.oidc.secret.annotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.oidc.secret.cookieSecretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{ .Values.oidc.secret.clientSecretKey }}: {{ randAlphaNum 32 | b64enc | quote }}

{{- end }}