# charts/gcp-project-base/templates/00-project.yaml
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: {{ .Values.project.name }} # This is the Project ID string that KCC creates in GCP.
  namespace: config-connector # KCC Project resources are typically managed in config-connector NS

  annotations:
    cnrm.cloud.google.com/organization-id: "{{ .Values.orgId }}"
    {{- if .Values.project.id }} # This 'id' field is for the numerical ID, hydrated after creation.
    cnrm.cloud.google.com/project-id: "{{ .Values.project.id }}" # For idempotency/referencing.
    {{- end }}
spec:
  billingAccountRef: { external: "billingAccounts/{{ .Values.billingAccountId }}" }
  folderRef: { name: {{ .Values.project.folderRef | replace "folders/" "" }} } # Points to a KCC Folder resource
  organizationId: {{ .Values.orgId }}
  displayName: "{{ .Values.project.gcpProjectName }}" # Display name in GCP Console
  service: # List of APIs to enable for this project
  {{- range .Values.project.apis }}
    - {{ . }}
  {{- end }}
