---
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringAlertPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "45405492545"
  name: "2004910259767712314"
spec:
  alertStrategy:
    autoClose: 1800s
  combiner: OR
  conditions:
  - conditionThreshold:
      aggregations:
      - alignmentPeriod: 300s
        crossSeriesReducer: REDUCE_MEAN
        perSeriesAligner: ALIGN_DELTA
      comparison: COMPARISON_GT
      duration: 300s
      filter: resource.type = "prometheus_target" AND metric.type = "prometheus.googleapis.com/echo_http_request_duration_seconds/histogram"
      thresholdValue: 5
      trigger:
        count: 1
    displayName: Prometheus Target - prometheus/echo_http_request_duration_seconds/histogram
    name: projects/neural-vista-433523-c1/alertPolicies/2004910259767712314/conditions/13175893093727070516
  displayName: prometheus/echo_http_request_duration_seconds/histogram [50TH PERCENTILE]
  enabled: true
  notificationChannels:
  - external: projects/neural-vista-433523-c1/notificationChannels/9357074570526256308
  resourceID: "2004910259767712314"
---
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringAlertPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "45405492545"
  name: "3186096191984177952"
spec:
  combiner: OR
  conditions:
  - conditionThreshold:
      aggregations:
      - alignmentPeriod: 60s
        crossSeriesReducer: REDUCE_MEAN
        perSeriesAligner: ALIGN_DELTA
      comparison: COMPARISON_GT
      duration: 0s
      filter: resource.type = "prometheus_target" AND metric.type = "prometheus.googleapis.com/echo_http_request_duration_seconds/histogram"
      thresholdValue: 0.05
      trigger:
        count: 1
    displayName: prometheus/echo_http_request_duration_seconds/histogram [MEAN]
    name: projects/neural-vista-433523-c1/alertPolicies/3186096191984177952/conditions/2500841309260506740
  displayName: prometheus/echo_http_request_duration_seconds/histogram [MEAN]
  enabled: true
  notificationChannels:
  - external: projects/neural-vista-433523-c1/notificationChannels/9357074570526256308
  resourceID: "3186096191984177952"
