{{- if .Values.project.enabled }}
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: {{ include "openlane-gcp-project.fullname" . }}
  namespace: {{ include "openlane-gcp-project.namespace" . }}
  annotations:
    {{- if .Values.project.autoCreateNetwork }}
    cnrm.cloud.google.com/auto-create-network: {{ .Values.project.autoCreateNetwork | quote }}
    {{- end }}
spec:
  name: {{ .Values.project.name | quote }}
  {{- if .Values.project.resourceID }}
  resourceID: {{ .Values.project.resourceID | quote }}
  {{- end }}
  billingAccountRef:
    external: {{ .Values.project.billingAccountRef.external | quote }}
  {{- if .Values.project.folderRef }}
  folderRef:
    external: {{ .Values.project.folderRef.external | quote }}
  {{- end }}
  {{- if .Values.project.organizationRef }}
  organizationRef:
    external: {{ .Values.project.organizationRef.external | quote }}
  {{- end }}
{{- end }}
