{{- if .Values.apiEnablement.enabled }}
{{- range $svc := .Values.apiEnablement.services }}
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: {{ $svc | quote }}  
  namespace: {{ include "gcp-project.namespace" $ }}
spec:
  service: {{ $svc | quote }}
  projectRef:
    external: {{ $.Values.project.resourceID | quote }}
---
{{- end }}
{{- end }}
