{{- if .Values.global.gsa.create }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.global.gsa.project }}
    {{- if .Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
    {{- if .Values.annotations }}
{{- .Values.annotations | toYaml | nindent 4 }}
    {{- end }}
  labels:
{{- include "workload-identity.labels" . | nindent 4 }}
  name: {{ .Values.global.gsa.name }}
  namespace: {{ include "workload-identity.namespace" . }}
spec:
  displayName:  {{ .Values.global.gsa.name }}
{{- end }}
