# Default values for the Load Balancer chart
# Enable or disable the entire chart (boolean)
enabled: true

# Global IP address configuration
globalAddress:
  # Name of the ComputeAddress resource (string)
  name: "openlane-lb-address"
  # GCP project ID (string)
  projectId: ""
  # Address type: EXTERNAL or INTERNAL (string)
  addressType: "EXTERNAL"
  # IP version: IPV4 or IPV6 (string)
  ipVersion: "IPV4"
  # Description for the address (string)
  description: ""
  # Network tier: PREMIUM or STANDARD (string)
  networkTier: "PREMIUM"
  # Prefix length for internal addresses (integer)
  prefixLength: 0
  # Purpose of address (string)
  purpose: ""
  # VPC network reference (string)
  networkRef:
    external: ""
  # Subnetwork reference (string)
  subnetworkRef:
    external: ""

# Global HTTP(S) load balancer settings
# Backend service configuration (map)
backendService:
  # Name of the BackendService (string)
  name: ""
  # Protocol: HTTP, HTTPS, or HTTP2 (string)
  protocol: "HTTP"
  # Port numbers (array of integers)
  ports: []
  # Health check reference name (string)
  healthCheck: ""
  # Enable CDN (boolean)
  enableCDN: false
  # Session affinity setting (string)
  sessionAffinity: "NONE"

# URL map configuration
urlMap:
  # Name of the URLMap (string)
  name: ""
  # Default service backend (string)
  defaultService: ""

# Target proxy configuration
httpProxy:
  # Name of the TargetHttpProxy (string)
  name: ""
httpsProxy:
  # Name of the TargetHttpsProxy (string)
  name: ""
  # SSL certificate references (array of strings)
  sslCertificates: []

# Global forwarding rules
forwardingRule:
  # Name of the GlobalForwardingRule (string)
  name: ""
  # IP protocol: TCP or UDP (string)
  IPProtocol: "TCP"
  # Port range (string)
  portRange: ""
  # Target proxy reference (string)
  target: ""
