# Default values for the Load Balancer chart
# Enable or disable the entire chart (boolean)

global:
  # -- Allows to deploy in another namespace than the release one
  # @default -- `nil`
  cnrmNamespace: ""
  # -- Google Project ID
  gcpProjectId: myprojectid
  # -- If true, Keep the resources even after the kcc resource deletion.
  abandon: true

# Global IP address configuration
globalAddress:
  # Whether to enable the global address (boolean)
  enabled: true
  # Name of the ComputeAddress resource (string)
  name: "openlane-lb-address"
  # GCP project ID (string)
  projectId: ""
  # Address type: EXTERNAL or INTERNAL (string)
  addressType: "EXTERNAL"
  # IP version: IPV4 or IPV6 (string)
  ipVersion: "IPV4"
  # Description for the address (string)
  description: ""
  # Network tier: PREMIUM or STANDARD (string)
  networkTier: "PREMIUM"
  # Prefix length for internal addresses (integer)
  prefixLength: 0
  # Purpose of address (string)
  purpose: ""
  # VPC network reference (string)
  networkRef:
    external: ""
  # Subnetwork reference (string)
  subnetworkRef:
    external: ""
  location: "global"  # Location for global addresses

# Managed SSL Certificate
managedSslCertificate:
  # Whether to enable the managed SSL certificate (boolean)
  enabled: true
  # Name of the ManagedSslCertificate resource (string)
  name: "openlane-ssl-cert"
  # domains to secure (array of strings)
  domains:
    - "example.com"
    - "www.example.com"
  # description for the certificate (string)
  description: ""

# SSL Policy
sslPolicy:
  # Whether to enable the ssl policy (boolean)
  enabled: true
  # Name of the SSL policy (string)
  name: "openlane-ssl-policy"
  # minimum TLS version (string)
  minTlsVersion: "TLS_1_3"
   # COMPATIBLE or MODERN
  profile: "MODERN"
  # e.g. TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  customFeatures: []

# Global HTTP(S) load balancer settings
# Backend service configuration (map)
backendService:
  # Whether to enable the backend service (boolean)
  enabled: true
  # Name of the BackendService (string)
  name: "openlane-backend-service"
  # Protocol: HTTP, HTTPS, or HTTP2 (string)
  protocol: "HTTP"
  # Port numbers (array of integers)
  ports: []
  # Health check reference name (string)
  healthCheck: ""
  # Enable CDN (boolean)
  enableCDN: false
  # Session affinity setting (string)
  sessionAffinity: "NONE"
  # ComputeInstanceGroup backends
  backends:
  # Instance group resource path
    - group:
        external: ""
      # UTILIZATION or RATE
      balancingMode: "UTILIZATION"
      maxUtilization: 0.8
      capacityScaler: 1.0

# Health Check
healthCheck:
  # Whether to enable the healthcheck (boolean)
  enabled: true
  # Name of the HealthCheck (string)
  name: "openlane-hc"
  # number of seconds between health checks (integer)
  checkIntervalSec: 10
  # number of seconds before a timeout (integer)
  timeoutSec: 5
  # number of consecutive successful checks before marking healthy (integer)
  healthyThreshold: 2
  # number of consecutive failed checks before marking unhealthy (integer)
  unhealthyThreshold: 2
  # tcpHealth Check configuration
  tcpHealthCheck: {}
  # httpHealthCheck configuration
  httpHealthCheck:
    # Port number (integer)
    port: 80
    # Request path for health check (string)
    requestPath: "/healthz"

# URL map configuration
urlMap:
  # Whether to enable the URL map (boolean)
  enabled: true
  # Name of the URLMap (string)
  name: "openlane-url-map"
  # Default service backend (string)
  defaultService: ""
  # Host-based routing
  hostRules:
    - hosts:
        - "example.com"
      pathMatcher: "default"

# HTTP target proxy configuration
targetHttpProxy:
  # Whether to enable the HTTP target proxy (boolean)
  enabled: true
  # Name of the TargetHttpProxy (string)
  name: "openlane-http-proxy"
  urlMap: ""

# HTTPS target proxy configuration
targetHttpsProxy:
  # Whether to enable the HTTPS target proxy (boolean)
  enabled: true
  # Name of the TargetHttpsProxy (string)
  name: "openlane-https-proxy"
  # SSL certificate references (array of strings)
  sslCertificates: []
  # URL map reference (string)
  urlMap: "openlane-url-map"

# Global forwarding rules
forwardingRuleHttp:
  # Whether to enable the HTTP forwarding rule (boolean)
  enabled: true
  # Name of the GlobalForwardingRule (string)
  name: "openlane-fr-http"
  # IP protocol: TCP or UDP (string)
  IPProtocol: "TCP"
  # Port range (string)
  portRange: "80-80"
  # Target proxy reference (string)
  target: ""

# Global forwarding rule
forwardingRuleHttps:
  # Whether to enable the HTTPS forwarding rule (boolean)
  enabled: true
  # Name of the GlobalForwardingRule (string)
  name: "openlane-fr-https"
  # IP protocol: TCP or UDP (string)
  IPProtocol: "TCP"
  # Port range (string)
  portRange: "443-443"
  # Target proxy reference (string)
  target: ""
