version: 0.1.1
apiVersion: v2
appVersion: 1.0.0
description: A Helm chart to deploy External Secrets Operator for Openlane
name: openlane-eso
type: application
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/openlane-infra
home: https://docs.theopenlane.io
dependencies:
  - name: external-secrets
    version: 0.20.1
    repository: https://charts.external-secrets.io
    alias: eso
