version: 1.0.0
apiVersion: v2
appVersion: 1.0.0
description: Helm chart for managing deployment of Windmill alongside Openlane
name: openlane-windmill
type: application
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/openlane-infra
home: https://docs.theopenlane.io
dependencies:
  - name: windmill
    version: 2.0.447
    repository: https://windmill-labs.github.io/windmill-helm-charts
