apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  annotations:
{{- if .Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
{{- end }}
    cnrm.cloud.google.com/project-id: {{ .Values.global.gcpProjectId | quote }}
{{- if .Values.global.skipUnspecifiedFields }}
    cnrm.cloud.google.com/state-into-spec: absent
{{- end }}
  labels:
{{- include "openlane-gcp-subnetwork.labels" . | nindent 4 }}
  name: {{ include "openlane-gcp-subnetwork.fullname" . }}
  namespace: {{ include "openlane-gcp-subnetwork.namespace" . }}
spec:
{{- if .Values.global.description }}
  description: {{ .Values.global.description }}
{{- end }}
  ipCidrRange: {{ .Values.ipCidrRange }}
{{- if .Values.ipv6AccessType }}
  ipv6AccessType: {{ .Values.ipv6AccessType }}
{{- end }}
{{- with .Values.logConfig }}
  logConfig:
{{- . | toYaml | nindent 4 }}
{{- end }}
{{- if .Values.networkRef }}
  networkRef:
    {{- if .Values.networkRef.external }}
    external: {{ .Values.networkRef.external | quote }}
    {{- end }}
    name: {{ .Values.networkRef.name | default "openlane-vpc" }}
    {{- if .Values.networkRef.namespace }}
    namespace: {{ .Values.networkRef.namespace }}
    {{- end }}
{{- end }}
{{- if .Values.privateIpGoogleAccess }}
  privateIpGoogleAccess: {{ .Values.privateIpGoogleAccess }}
{{- end }}
{{- if .Values.privateIpv6GoogleAccess }}
  privateIpv6GoogleAccess: {{ .Values.privateIpv6GoogleAccess }}
{{- end }}
{{- if .Values.purpose }}
  purpose: {{ .Values.purpose }}
{{- end }}
  region: {{ .Values.region | quote }}
{{- if .Values.resourceID }}
  resourceID: {{ .Values.resourceID }}
{{- end }}
{{- if .Values.role }}
  role: {{ .Values.role }}
{{- end }}
  secondaryIpRange:
{{- range .Values.secondaryIpRange }}
  - ipCidrRange: {{ .ipCidrRange }}
    rangeName: {{ .rangeName }}
{{- end }}
{{- if .Values.stackType }}
  stackType: {{ .Values.stackType }}
{{- end }}
