grafana:
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    auth:
      disable_login_form: true
      disable_signout_menu: false
    auth.proxy:
      enabled: true
      header_name: X-Auth-Request-Email
      auto_sign_up: true
      sync_ttl: 60
      whitelist: ""
    server:
      root_url: https://grafana.theopenlane.org
    paths:
      data: /var/lib/grafana/data
    analytics:
      check_for_updates: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Google Cloud Monitoring
          type: stackdriver
          access: proxy
          isDefault: true
          jsonData:
            authenticationType: gce
            defaultProject: prod-apps-project

# leaving this here as it's how i crated the http route
  ingress:
    enabled: false
    ingressClassName: gce
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: grafana.theopenlane.org
    hosts:
      - grafana.theopenlane.org
    tls:
      - hosts:
          - grafana.theopenlane.org
        secretName: grafana-tls

  persistence:
    enabled: true
    size: 10Gi

oauth2:
  config:
    existingSecret: grafana-app-secret
    cookieSecret: L0RBTFc2NVNCWDkrSDJDNG9zeFBHWFYrK3p4WFcxS0w=
    provider: google
    emailDomains:
      - theopenlane.org
      - theopenlane.io
    whitelistDomains:
      - .theopenlane.org
      - .theopenlane.io
    redirectURL: https://grafana.theopenlane.org/oauth2/callback
    upstreams:
      - http://grafana.default.svc.cluster.local:3000/

# leaving this here as it's how i crated the oauth2 route
  ingress:
    enabled: true
    ingressClassName: gce
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: grafana.theopenlane.org
    hosts:
      - grafana.theopenlane.org
    tls:
      - hosts:
          - grafana.theopenlane.org
        secretName: grafana-tls
