grafana:
  admin:
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    auth:
      disable_login_form: true
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
      org_role: "Admin"
    auth.proxy:
      enabled: true
      header_name: X-Auth-Request-Email
      auto_sign_up: true
      sync_ttl: 60
      whitelist: ""
    server:
      root_url: https://grafana.theopenlane.org
    paths:
      data: /var/lib/grafana/data
    analytics:
      check_for_updates: true
    users:
      auto_assign_org_role: Admin

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Google Cloud Monitoring
          type: stackdriver
          access: proxy
          editable: true
          orgId: 1
          isDefault: true
          jsonData:
            authenticationType: gce
            defaultProject: prod-apps-project

  persistence:
    enabled: true
    size: 10Gi

  plugins:
    - grafana-clock-panel
    - digrich-bubblechart-panel
    - natel-discrete-panel
    - pr0ps-trackmap-panel
    - grafana-piechart-panel
    - vonage-status-panel
    - grafana-worldmap-panel

oauth2:
  config:
    existingSecret: grafana-app-secret
    provider: google
    configFile: |-
      set_xauthrequest = true
      skip_auth_preflight = true
      redirect_url = "https://grafana.theopenlane.org/oauth2/callback"
      upstreams = [ "http://grafana:80/" ]
      whitelist_domains = [ "*.theopenlane.org" ]
      email_domains = [ "*" ]


# leaving this here as it's how i crated the oauth2 route
  ingress:
    enabled: false
    ingressClassName: gce
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: grafana.theopenlane.org
    hosts:
      - grafana.theopenlane.org
    tls:
      - hosts:
          - grafana.theopenlane.org
        secretName: grafana-tls
