remote: origin
target-branch: main
chart-dirs:
  - charts

chart-repos:
 - external-secrets=https://charts.external-secrets.io
 - dex=https://charts.dexidp.io
 - argo-cd=https://argoproj.github.io/argo-helm
 - cert-manager=https://charts.jetstack.io
 - kube-prometheus-stack=https://prometheus-community.github.io/helm-charts
 - oauth2-proxy=https://oauth2-proxy.github.io/manifests
 - grafana=https://grafana.github.io/helm-charts
 - ingress-nginx=https://kubernetes.github.io/ingress-nginx
 - external-dns=https://kubernetes-sigs.github.io/external-dns/
helm-extra-args: "--timeout 600s"
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false
