remote: origin
target-branch: main
chart-dirs:
  - charts

chart-repos:
 - argo-cd=https://argoproj.github.io/argo-helm
 - cert-manager=https://charts.jetstack.io
 - external-dns=https://kubernetes-sigs.github.io/external-dns/
 - openlane-infra=https://theopenlane.github.io/openlane-infra
helm-extra-args: "--timeout 900s"
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false
