apiVersion: v2
appVersion: 0.1.0
description: A Helm chart that Creates a Google Service Account and it's Key through Config Connector
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
name: openlane-gcp-service-account
type: application
version: 0.1.1
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/core
  - https://github.com/theopenlane/openlane-infra
home: https://www.theopenlane.io
