{{- if not $.Values.enableAutopilot }}
{{- range .Values.nodePools -}}
{{ if .nodeConfig.serviceAccount.create }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .nodeConfig.serviceAccount.name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ $.Values.global.gcpProjectId }}
    {{- if $.Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
  labels:
{{- include "gcp-gke-cluster.labels" $ | nindent 4 }}
spec:
  displayName: {{ .nodeConfig.serviceAccount.name }}

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ $.Values.global.gcpProjectId }}
    {{- if $.Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
  name: {{ .nodeConfig.serviceAccount.name }}-container-node-binding
  labels:
{{- include "gcp-gke-cluster.labels" $ | nindent 4 }}
spec:
  member: serviceAccount:{{ .nodeConfig.serviceAccount.name }}@{{ $.Values.global.gcpProjectId }}.iam.gserviceaccount.com
  role: roles/container.nodeServiceAccount
  resourceRef:
    kind: Project
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: {{ $.Values.global.gcpProjectId }}
{{- end -}}
{{- end -}}
{{- end -}}

{{- if and $.Values.enableAutopilot }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ $.Values.clusterAutoscaling.serviceAccountRef.name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ $.Values.global.gcpProjectId }}
    {{- if $.Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
  labels:
{{- include "gcp-gke-cluster.labels" $ | nindent 4 }}
spec:
  displayName: {{ $.Values.clusterAutoscaling.serviceAccountRef.name }}

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ $.Values.global.gcpProjectId }}
    {{- if $.Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
    {{- end }}
  name: {{ $.Values.clusterAutoscaling.serviceAccountRef.name }}-container-node-binding
  labels:
{{- include "gcp-gke-cluster.labels" $ | nindent 4 }}
spec:
  member: serviceAccount:{{ $.Values.clusterAutoscaling.serviceAccountRef.name }}@{{ $.Values.global.gcpProjectId }}.iam.gserviceaccount.com
  role: roles/container.nodeServiceAccount
  resourceRef:
    kind: Project
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: {{ $.Values.global.gcpProjectId }}
{{- end -}}
