apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
{{- if .Values.global.abandon }}
    cnrm.cloud.google.com/deletion-policy: abandon
{{- end }}
    cnrm.cloud.google.com/project-id: {{ .Values.global.gcpProjectId | quote }}
{{- if .Values.global.skipUnspecifiedFields }}
    cnrm.cloud.google.com/state-into-spec: absent
{{- end }}
  labels:
{{- include "gcp-vpc-network.labels" . | nindent 4 }}
  name: {{ include "gcp-vpc-network.fullname" . }}
  namespace: {{ include "gcp-vpc-network.namespace" . }}
spec:
  autoCreateSubnetworks: {{ .Values.autoCreateSubnetworks }}
  deleteDefaultRoutesOnCreate: {{ .Values.deleteDefaultRoutesOnCreate }}
  mtu: {{ .Values.mtu }}
  routingMode: {{ .Values.routingMode | quote }}
  enableUlaInternalIpv6: {{ .Values.enableUlaInternalIpv6 }}
  internalIpv6Range: {{ .Values.internalIpv6Range | quote }}
  networkFirewallPolicyEnforcementOrder: {{ .Values.networkFirewallPolicyEnforcementOrder | quote }}
  resourceID: {{ .Values.resourceID | quote }}