global:
  # -- Allows to deploy in another namespace than the release one
  # @default -- `nil`
  cnrmNamespace: ""
  # -- Google Project ID
  gcpProjectId: myprojectid
  # -- Keep the VPC even after the kcc resource deletion.
  abandon: false

# -- Name of the VPC Network.
name: "openlane-vpc"
# -- The display name for the VPC Network. Can be updated without creating a new resource.
displayName: "OPENLANE VPC"
# -- A text description of the VPC Network. Must be less than or equal to 256 UTF-8 bytes.
description: "OPENLANE VPC Network for infrastructure."

# -- Enable custom subnet creation. If false, the VPC Network will not create subnets.
autoCreateSubnetworks: false
# -- Keep the default routes on creation by default. If true, the VPC Network will delete the default routes.
deleteDefaultRoutesOnCreate: false
# -- Maximum Transmission Unit in bytes.
mtu: 1460
# -- Routing mode for the VPC Network.
routingMode: "REGIONAL"
# -- Enable ULA internal ipv6 on this network.
enableUlaInternalIpv6: false
# -- Internal IPv6 range for ULA internal ipv6.
internalIpv6Range: ""
# -- The order that Firewall Rules and Firewall Policies are evaluated. Default value: "AFTER_CLASSIC_FIREWALL" Possible values: ["BEFORE_CLASSIC_FIREWALL", "AFTER_CLASSIC_FIREWALL"].
networkFirewallPolicyEnforcementOrder: "AFTER_CLASSIC_FIREWALL"
# -- Optional resource ID.
resourceID: ""

# -- Add annotations to the VPC Network.
annotations: {}

firewallRules:
  enabled: true
  rules:
  # -- Allow internal communication within the VPC network (essential for GKE pod communication).
  - name: "allow-internal-all"
    description: "Allow all internal traffic within the VPC."
    direction: "INGRESS"
    priority: 1000
    sourceRanges:
      - "10.0.0.0/8"
    allowed:
      - protocol: "all"
    targetTags: []

  # -- Allow ingress from GKE masters to nodes (required by GKE).
  - name: "allow-gke-master-ingress"
    description: "Allow GKE master ingress to nodes."
    direction: "INGRESS"
    priority: 1000
    # GKE master CIDR block is dynamic, use Google-recommended static ranges + your VPC CIDR
    sourceRanges:
      - "130.211.0.0/22"
      - "35.191.0.0/16"
      # Consider adding your GKE master authorized network if explicitly set in cluster.
    targetTags:
      - 'gke-{{ .Values.network.projectId }}-{{ include "gcp-gke-prod-cluster.fullname" . }}-node'
    allowed:
      - protocol: "tcp"
        ports: ["1-65535"]
      - protocol: "udp"
        ports: ["1-65535"]
      - protocol: "icmp"

  # -- Allow ephemeral ports (for health checks from load balancer)
  - name: "allow-health-check-ingress"
    description: "Allow ingress for health checks from GCP Load Balancer."
    direction: "INGRESS"
    priority: 1000
    sourceRanges:
      - "130.211.0.0/22"
      - "35.191.0.0/16"
    allowed:
      - protocol: "tcp"
        ports: ["80", "443", "8080"]
    targetTags: []

  # -- Default allow egress to all (securely restrict this where possible)
  - name: "allow-egress-all"
    description: "Allow all egress traffic."
    direction: "EGRESS"
    priority: 1000
    destinationRanges:
      - "0.0.0.0/0"
    allowed:
      - protocol: "all"
    targetTags: []

# -- Shared VPC configuration
sharedVPC:
  # -- Enable this project as a Shared VPC Host.
  host:
    enabled: false
  # -- Enable this project as a Shared VPC Service.
  service:
    enabled: false
    # -- The reference to the host project.
    hostProjectRef:
      external: ""
    # -- The reference to the host network in the Shared VPC Host project.
    hostNetworkRef:
      external: "openlane-network"
