apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for cert-manager
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
name: openlane-cert-manager
type: application
version: 0.1.2
dependencies:
  - name: cert-manager
    version: "v1.17.2"
    repository: "https://charts.jetstack.io"
    alias: certmanager
  - name: openlane-gcp-workload-identity
    version: 0.1.1
    repository: "https://theopenlane.github.io/openlane-infra"
    alias: workloadIdentity
    tags:
      - configConnector
  - name: openlane-gcp-iam-policy-members
    version: 0.1.1
    repository: "https://theopenlane.github.io/openlane-infra"
    alias: iamPolicyMembers
    tags:
      - configConnector
