remote: origin
chart-dirs:
  - charts
helm-extra-args: --timeout=500
chart-repos:
  - cert-manager=https://charts.jetstack.io
  - openlane-helm=https://openlane.github.io/openlane-helm
check-version-increment: true
