apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: core-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: signing-token-eddsa
spec:
  secretName: token-keys-eddsa
  commonName: core-token
  privateKey:
    algorithm: Ed25519
    encoding: PKCS8
  usages:
    - digital signature
  issuerRef:
    name: core-selfsigned
    kind: Issuer
    group: cert-manager.io
