apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: core-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: signing-token
spec:
  secretName: token-keys
  commonName: core-token
  privateKey:
    algorithm: RSA
    size: 4096
    encoding: PKCS8
  usages:
    - digital signature
  issuerRef:
    name: core-selfsigned
    kind: Issuer
    group: cert-manager.io
