apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openlane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.openlane.replicaCount }}
  selector:
    matchLabels:
      {{- include "openlane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openlane.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.openlane.serviceAccountName }}
      containers:
        - name: openlane
          args:
            - serve
          envFrom:
            - secretRef:
                name: openlane-app-secret
          image: ghcr.io/theopenlane/core:v0.17.0
          imagePullPolicy: Always
          startupProbe:
            failureThreshold: 1
            initialDelaySeconds: 0
            periodSeconds: 240
            tcpSocket:
              port: 17608
            timeoutSeconds: 240
          ports:
            - containerPort: 17608
              protocol: TCP
              name: http
            - containerPort: 17609
              protocol: TCP
              name: metrics
