apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openlane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.openlane.replicaCount }}
  selector:
    matchLabels:
      {{- include "openlane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openlane.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: openlane
          args:
            - serve
          envFrom:
            - secretRef:
                name: openlane-app-secret
          image: ghcr.io/theopenlane/core:v0.17.1
          imagePullPolicy: Always
          ports:
            - containerPort: 17608
              protocol: TCP
              name: http
            - containerPort: 17609
              protocol: TCP
              name: metrics
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
