apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlane-app
  namespace: openlane
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: {{ .Release.Name }}
          app.kubernetes.io/instance: {{ .Release.Name }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Release.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
            - name: openlane-app
              args:
                - serve
              envFrom:
                - secretRef:
                    name: openlane-app-secret
              image: ghcr.io/theopenlane/core:v0.17.0
              imagePullPolicy: Always
              startupProbe:
                failureThreshold: 1
                initialDelaySeconds: 0
                periodSeconds: 240
                tcpSocket:
                  port: 17608
                timeoutSeconds: 240
              ports:
                - containerPort: 17608
                  protocol: TCP
                  name: http
                - containerPort: 17609
                  protocol: TCP
                  name: metrics

