apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: openlane-healthcheck
  namespace: openlane
spec:
  default:
    unhealthyThreshold: 10
    healthyThreshold: 1
    timeoutSec: 5
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /livez
        port: 80
        portSpecification: USE_FIXED_PORT
  targetRef:
    group: ""
    kind: Service
    name: prod-openlane
