apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openlane-route
  labels:
    gateway: prod-central1-core-gateway
  namespace: openlane
spec:
  parentRefs:
  - name: prod-central1-core-gateway
    namespace: gateway-system
    sectionName: https
  hostnames:
  - "api.theopenlane.io"
  - "api.prod.theopenlane.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: prod-openlane
      port: 80
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: openlane-cf-whitelist
  namespace: openlane
  labels:
    gateway: prod-central1-core-gateway
spec:
  targetRef:
    group: ""
    kind: Service
    name: prod-openlane
  default:
    securityPolicy: restrict-to-cloudflare
