apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openlane-route
  labels:
    gateway: prod-global-gateway
  namespace: openlane
spec:
  parentRefs:
  - name: prod-global-gateway
    namespace: argocd
    sectionName: https
  hostnames:
  - "api.theopenlane.io"
  - "api.prod.theopenlane.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: prod-openlane
      port: 80
  healthCheckPolicy:
    path: /livez
    port: 80
