apiVersion: v1
kind: Service
metadata:
  name: prod-openlane
  namespace: openlane
  labels:
    {{- include "openlane.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default": "openlane-backendconfig"}'
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 17608
  - name: https
    protocol: TCP
    port: 443
    targetPort: 17608
  selector:
    {{- include "openlane.selectorLabels" . | nindent 4 }}
