apiVersion: v1
kind: Service
metadata:
  name: prod-openlane-clusterip
  namespace: openlane
  labels:
    app.kubernetes.io/name: openlane
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 17608
  - name: https
    protocol: TCP
    port: 443
    targetPort: 17608
  selector:
    app.kubernetes.io/name: openlane
