apiVersion: v1
kind: ServiceAccount
metadata:
  name: openlane-gke-deployment-sa
  namespace: openlane
  annotations:
    iam.gke.io/gcp-service-account: openlane-gke-deployment-sa@yprod-apps-project.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openlane-namespace-admin
  namespace: openlane
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openlane-namespace-admin-binding
  namespace: openlane
subjects:
  - kind: ServiceAccount
    name: openlane-gke-deployment-sa
    namespace: openlane
roleRef:
  kind: Role
  name: openlane-namespace-admin
  apiGroup: rbac.authorization.k8s.io
