apiVersion: v1
kind: Service
metadata:
  name: prod-riverboat-ui
  namespace: openlane
  labels:
    {{- include "riverboatui.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    {{- include "riverboatui.selectorLabels" . | nindent 4 }}
