apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-riverboat
  namespace: openlane
  labels:
    {{- include "riverboat.labels" . | nindent 4 }}
  annotations:
    # This checksum will trigger deployment restarts when the ConfigMap changes
    checksum/config: {{ .Values | toYaml | sha256sum }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.riverboat.replicaCount }}
  selector:
    matchLabels:
      {{- include "riverboat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "riverboat.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - serve
          envFrom:
          {{- if .Values.riverboat.secret.create }}
            - secretRef:
                name: {{ .Values.riverboat.secret.name }}
          {{- end }}
          {{- if .Values.riverboat.config.create }}
            - configMapRef:
                name: {{ .Values.riverboat.config.name }}
          {{- end }}
          image: {{ .Values.riverboat.image.repository }}:{{ .Values.riverboat.image.tag }}
          imagePullPolicy: Always
          name: riverboat
