apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-riverboat
  namespace: openlane
  labels:
    {{- include "riverboat.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.riverboat.replicaCount }}
  selector:
    matchLabels:
      {{- include "riverboat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "riverboat.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - serve
          env:
            - name: RIVERBOAT_RIVER_WORKERS_DELETEEXPORTCONTENTWORKER_CONFIG_ENABLED
              value: "true"
            - name: RIVERBOAT_RIVER_WORKERS_DELETEEXPORTCONTENTWORKER_CONFIG_INTERVAL
              value: "300000000000" # 5 minutes
            - name: RIVERBOAT_RIVER_WORKERS_DELETEEXPORTCONTENTWORKER_CONFIG_CUTOFFDURATION
              value: "1800000000000" # 30 minutes
            - name: RIVERBOAT_RIVER_WORKERS_EXPORTCONTENTWORKER_CONFIG_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: riverboat-app-secret
          image: {{ .Values.riverboat.image.repository }}:{{ .Values.riverboat.image.tag }}
          imagePullPolicy: Always
          name: riverboat
