---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: riverboatui-app-secret-ext
  namespace: openlane
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: riverboatui-app-secret
    creationPolicy: Owner
  data:
  - secretKey: RIVER_BASIC_AUTH_USER
    remoteRef:
      key: RIVER_BASIC_AUTH_USER
  - secretKey: RIVER_BASIC_AUTH_PASS
    remoteRef:
      key: RIVER_BASIC_AUTH_PASS
