apiVersion: v1
kind: Service
metadata:
  name: prod-openlane
  namespace: openlane
  labels:
    {{- include "openlane.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort
  sessionAffinity: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 17608
  - name: https
    protocol: TCP
    port: 443
    targetPort: 17608
  selector:
    app.kubernetes.io/name: openlane-app
    app.kubernetes.io/instance: openlane-app
