apiVersion: v2
appVersion: 3.0.3
description: A Helm chart for Kubernetes
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
name: openlane-argocd
type: application
version: 0.1.2
dependencies:
  - name: argo-cd
    version: 8.0.13
    repository: "https://argoproj.github.io/argo-helm"
    alias: argocd
