apiVersion: v2
name: trustcenter-gateway
description: A Helm chart for deploying the necessary components to run the Trustcenter Gateway
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
  - email: support@theopenlane.io
    name: Openlane
    url: https://www.theopenlane.io
icon: https://raw.githubusercontent.com/theopenlane/openlane-infra/refs/heads/main/assets/favicon.ico
sources:
  - https://github.com/theopenlane/core
home: https://docs.theopenlane.io
