apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-secretsstore-sa
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: prod-gke-central1@prod-apps-project.iam.gserviceaccount.com
    argo-cd.argoproj.io/sync-wave: "-1"
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: prod-apps-project
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: prod-central1-core
          clusterProjectID: prod-apps-project
          serviceAccountRef:
            name: gcp-secretsstore-sa
            namespace: external-secrets
