apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openlane-app-secrets
  namespace: openlane
spec:
  encryptedData:
    PLACEHOLDER_KEY: Ag...==
  template:
    metadata:
      name: openlane-app-secrets
      namespace: openlane
    type: Opaque
