apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-gcp-secrets
  namespace: default
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/my-project/secrets/api-key"
        version: "latest"
    # For a KMS-encrypted payload in Cloud Storage:
    # - resourceName: "projects/my-project/locations/global/keyRings/my-ring/cryptoKeys/my-key"
    #   filePath: "gs://my-bucket/path/to/encrypted-file"
