apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openlane-infra
  namespace: argocd
spec:
  description: Openlane infrastructure charts
  sourceRepos:
    - https://github.com/theopenlane/openlane-infra.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
