apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: openlane-infra
  source:
    repoURL: https://github.com/theopenlane/openlane-infra.git
    targetRevision: main
    path: charts/cert-manager
    helm:
      releaseName: cert-manager
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
