apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: openlane-infra
  source:
    repoURL: https://github.com/theopenlane/openlane-infra.git
    targetRevision: main
    path: charts/external-dns
    helm:
      releaseName: external-dns
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
#    automated: don't autosync
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
