apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: openlane-infra
  source:
    repoURL: https://github.com/theopenlane/openlane-infra.git
    targetRevision: main
    path: charts/eso
    helm:
      releaseName: external-secrets
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      enable: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
