apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlane
  namespace: argocd
spec:
  project: openlane-infra
  source:
    repoURL: https://github.com/theopenlane/openlane-infra.git
    targetRevision: main
    path: charts/openlane
    helm:
      releaseName: openlane
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openlane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
