apiVersion: v1
kind: Secret
metadata:
  name: openlane-infra-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/theopenlane/openlane-infra.git
  type: git
